{
  boolean fail=false;
  try {
    future.actionGet();
    fail=true;
  }
 catch (  ElasticSearchException esException) {
    assertThat(esException.unwrapCause(),instanceOf(exceptionClass));
  }
catch (  Throwable e) {
    assertThat(e,instanceOf(exceptionClass));
  }
  if (fail)   throw new AssertionError("Expected a " + exceptionClass + " exception to be thrown");
}
