{
  try {
    result=callable.call();
    return true;
  }
 catch (  Error err) {
    throw err;
  }
catch (  RuntimeException rex) {
    throw rex;
  }
catch (  Exception ex) {
    throw new RuntimeException(ex);
  }
}
