{
  try {
    exec("int x = -10; int y = 2147483647; return x - y;");
    fail("should have hit exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = -10L; long y = 9223372036854775807L; return x - y;");
    fail("should have hit exception");
  }
 catch (  ArithmeticException expected) {
  }
}
