{
  RuntimeException exception=new RuntimeException();
  Callable<?> afterCallable=mock(Callable.class);
  AbstractRunnable runnable=new AbstractRunnable(){
    @Override public void onFailure(    Exception e){
      assertSame(exception,e);
    }
    @Override protected void doRun() throws Exception {
      throw exception;
    }
    @Override public void onAfter(){
      try {
        afterCallable.call();
      }
 catch (      Exception e) {
        fail(e.toString());
      }
    }
  }
;
  runnable.run();
  verify(afterCallable).call();
}
