{
  try {
    exec("byte x = 127; ++x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("byte x = 127; x++; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("byte x = (byte) -128; --x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("byte x = (byte) -128; x--; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("short x = 32767; ++x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("short x = 32767; x++; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("short x = (short) -32768; --x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("short x = (short) -32768; x--; return x;");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = 65535; ++x; return x;");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = 65535; x++; return x;");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = (char) 0; --x; return x;");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = (char) 0; x--; return x;");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = 2147483647; ++x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = 2147483647; x++; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = (int) -2147483648L; --x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = (int) -2147483648L; x--; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = 9223372036854775807L; ++x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = 9223372036854775807L; x++; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = -9223372036854775807L - 1L; --x; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = -9223372036854775807L - 1L; x--; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
}
