{
  assertEquals(5L / 2L,Utility.divideWithoutOverflow(5L,2L));
  try {
    Utility.divideWithoutOverflow(Long.MIN_VALUE,-1L);
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    Utility.divideWithoutOverflow(5L,0L);
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
}
