{
  for (  MembershipAction.JoinCallback callback : callbacks) {
    try {
      callback.onFailure(e);
    }
 catch (    Exception inner) {
      logger.error("error handling task failure [{}]",inner,e);
    }
  }
}
