{
  assertEquals(5 / 2,Utility.divideWithoutOverflow(5,2));
  try {
    Utility.divideWithoutOverflow(Integer.MIN_VALUE,-1);
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    Utility.divideWithoutOverflow(5,0);
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
}
