{
  try {
    updateFuture.actionGet(WAIT_FOR_RESPONSE_TIMEOUT);
    fail("Future for update request did not complete exceptionally, but should.");
  }
 catch (  ElasticsearchTimeoutException e) {
    fail("Future for update request did not complete within " + WAIT_FOR_RESPONSE_TIMEOUT);
  }
catch (  Exception e) {
    assertTrue("Future for update request completed with an unexpected exception.",expectedExceptionClass.isInstance(e));
  }
}
