{
  if (t instanceof RetryOnReplicaException) {
    logger.trace("Retrying operation on replica",t);
    observer.waitForNextChange(new ClusterStateObserver.Listener(){
      @Override public void onNewClusterState(      ClusterState state){
        threadPool.executor(executor).execute(AsyncReplicaAction.this);
      }
      @Override public void onClusterServiceClose(){
        responseWithFailure(new NodeClosedException(clusterService.localNode()));
      }
      @Override public void onTimeout(      TimeValue timeout){
        throw new AssertionError("Cannot happen: there is not timeout");
      }
    }
);
  }
 else {
    try {
      failReplicaIfNeeded(request.internalShardId.getIndex(),request.internalShardId.id(),t);
    }
 catch (    Throwable unexpected) {
      logger.error("{} unexpected error while failing replica",request.internalShardId.id(),unexpected);
    }
 finally {
      responseWithFailure(t);
    }
  }
}
